### ISSUE TITLE
ZIP Codes should be treated as strings

### ISSUE THREAD

**Issue by JoeGermuska** [altair-viz/vega_datasets#19]
When the `zipcodes` data is loaded, it returns a dataframe with integer values for the `zip_code` column.
![image](https://user-images.githubusercontent.com/46313/45173041-abe29c80-b1cc-11e8-9c3b-67a9520ba705.png)

These values should be five-character strings. Is there a reasonable way to make this package control for that?

in the meantime, this is a simple workaround:
`df['zip_code'] = df['zip_code'].apply(lambda x: str(x).zfill(5))`

**Comment by jakevdp** [comment]
Thanks for the report – this has been addressed in #17, though that fix has not yet made it into a release.
