### ISSUE TITLE
Consider using CDN for the base url

### ISSUE THREAD

**Issue by eitanlees** [altair-viz/vega_datasets#41]
In [vega/vega-datasets](https://github.com/vega/vega-datasets) they recommend using a CDN with a fixed version to access the URLs for a dataset such as 

https://cdn.jsdelivr.net/npm/vega-datasets@1.31/data/cars.json

instead of 

https://vega.github.io/vega-datasets/data/cars.json

I was wondering if we should make this change as well?

I think modifications would take place here:

https://github.com/altair-viz/vega_datasets/blob/70d6829f9a158c7e07f56291ce02c9bcd019acdd/vega_datasets/core.py#L94

but it would be cool if it could grab the correct version number from 

https://github.com/altair-viz/vega_datasets/blob/70d6829f9a158c7e07f56291ce02c9bcd019acdd/vega_datasets/__init__.py#L9

Anyways, just an idea moving forward to try to make things more stable

**Comment by jakevdp** [comment]
This makes a lot of sense. Should we make a 1.X release with this change before updating to 2.0?

**Comment by eitanlees** [comment]
Yeah, I think that's a good idea

**Comment by eitanlees** [comment]
Is it possible to grab the variable `SOURCE_TAG` from `__inti__.py` and use it in `core.py`?

**Comment by jakevdp** [comment]
Sure, that seems reasonable.

**Comment by eitanlees** [comment]
Ok. I am away from my computer now but I will try to send a PR later today or tomorrow.
